import {
  DECK_DELETE_ENDPOINT,
  DECK_FIND_ALL_ENDPOINT,
  DECK_FIND_BY_ID_ENDPOINT,
  DECK_FIND_RANDOM_ENDPOINT,
  DECK_NEW_ENDPOINT,
  DECK_UPDATE_ENDPOINT,
  GAME_DELETE_ENDPOINT,
  GAME_FIND_ALL_ENDPOINT,
  GAME_FIND_BY_ID_ENDPOINT,
  GAME_NEW_ENDPOINT,
  GAME_UPDATE_ENDPOINT,
  MOXFIELD_ENDPOINT,
  PLAYER_DELETE_ENDPOINT,
  PLAYER_FIND_ALL_ENDPOINT,
  PLAYER_FIND_BY_ID_ENDPOINT,
  PLAYER_NEW_ENDPOINT,
  PLAYER_UPDATE_ENDPOINT
} from '../constants';

export class AuthenticationUtils {

  public static adminEndpoints(): string[] {
    return [
      DECK_DELETE_ENDPOINT,
      DECK_NEW_ENDPOINT,
      DECK_UPDATE_ENDPOINT,
      GAME_DELETE_ENDPOINT,
      GAME_UPDATE_ENDPOINT,
      MOXFIELD_ENDPOINT,
      PLAYER_DELETE_ENDPOINT,
      PLAYER_NEW_ENDPOINT,
      PLAYER_UPDATE_ENDPOINT
    ];
  }

  public static permittedEndpoints(): string[] {
    return [
      DECK_FIND_ALL_ENDPOINT,
      DECK_FIND_BY_ID_ENDPOINT,
      DECK_FIND_RANDOM_ENDPOINT,
      GAME_FIND_ALL_ENDPOINT,
      GAME_FIND_BY_ID_ENDPOINT,
      GAME_NEW_ENDPOINT,
      PLAYER_FIND_ALL_ENDPOINT,
      PLAYER_FIND_BY_ID_ENDPOINT
    ];
  }

}
